---
title: "README *functions*"
author: "M. G. Wellens"
date: "24 augustus 2018"
output: html_document
---


## Structure of directory
This folder contains the functions used to calculated different measures on networks. Every script depends on the files from *system*. The folder contains the following files:

+ *analyse\.R*: R script containing functions to analyse the behaviour of measures and graphs when a subgraph is used instead of the full graph. Usefull for error analyses when measuring the effect of incomplete data.  

    Functions:
    + *sample\_performance*: Simulates a number of random subgraphs of different sizes and calculates their performance. This function is parallellised.
    + *analyse\_sample\_performance*: Wrapper of *sample_performance* that picks up the data, analyses it and plots it into multiplee boxplots showing the distributions of performance as a function of subgraph size. It also outputs a file with the raw data from *sample\_performance*. This function itself is not parallellised, but it uses the parallellisation of *sample\_performance* for speed.
    
+ *measures\_distance\.R*: R script with measurements using a notion of distance in the graph. 

    Functions:
    + *global\_efficiency*: Calculates global efficiency using parallel computing. It therefore needs a cluster (for example, from *start\_cluster*). Does not accept length and/or transport matrices.
    + *global\_efficiency\_unpar*: Basics global efficiency function. It is not parallellised, but accepts length and/or transport matrices as optional arguments.
    + *local\_efficency*: Basic local efficiency function. Calculates global efficiency of the n-th order neighbourhoods of every node. Accepts length and/or transport matrices.
    
+ *measures\_topology\.R*: R script with measurements using only the topology of the graph, i.e. how nodes and edges are connected. The Kolmogorov complexity from *OACC* is loaded when this file is loaded. 

    Functions: 
    + *information\_content*: Calculates the *log2* of the number of automorphisms of the network, i.e. the *log2* of the number of permutations of nodes which keep the incidence structure intact (if A and B are connected/unconnected, then f(A) and f(B) are connected/unconnected).
    + *kolmogorov*: Function to calculate an upper bound for the Kolmogorov complexity of a graph using the algorithm of *OACC*, possibly normalised using a constant. Basically a wrapper of the *bdm2D* function from *OACC* with a normalisation constant added.
    + *kolmogorov_norm*: Simulates a number of Erdos-Renyi graphs to calculate the mean and standard deviation of their Kolmogorov complexity (using the *OACC* algorithm). Meant to be used in conjunction with *kolmogorov*, because the Kolmogorov complexity is highly dependent on the number of nodes and edges of a network. This function is parallellised.

+ *OACC*: A directory containing an algorithm to calculate an upper bound of the Kolmogorov complexity of a graph. To load the algorithm, use 

        setwd("functions/OACC");source("scripts/BDM2D\.R");setwd("\.\./\.\./"). 
    
    This algorithm is taken from 

        + Soler-Toscano F., Zenil H., Delahaye J.-P. and Gauvrit N. (2014) Calculating Kolmogorov Complexity from the Output Frequency Distributions of Small Turing Machines. PLoS ONE 9(5): e96223.

        + Gauvrit, N., Singmann H., Soler-Toscano F. and Zenil H.(2015) Algorithmic complexity for psychology: A user-friendly implementation of the coding theorem method, Behavior Research Methods, vol. 48, pp. 1–16.

        + Zenil H., Soler-Toscano F., Kiani N.A., Hernández-Orozco S., Rueda-Toicen A. (2016) A Decomposition Method for Global Evaluation of Shannon Entropy and Local Estimations of Algorithmic Complexity, arXiv:1609.00110.

+ *README\.rmd*: A RMarkdown README file.
+ *test\_distance\.R*: R script with vulnerability tests using a measure on a graph. The vulnerability is calculated by *1-p'/p*, where *p* is the performance of whole network and *p'* the performance of the damaged network. 

    Functions:
    + *vulnerability\_nodes*: Calculates for every node the damage done on a graph by removing that node, where the damage is measured by a measure. Technically, the nodes itself are not deleted, only the edges that are coincent to the node (starting from/going to the node for directed graphs), so the damage done by not being able to go to that particular node is incorporated into the vulnerability. This function is parallellised.
    + *vulnerability\_edges*: Calculates for every edge the damage done on a graph by remove that edge, where the damage is measured by a measure. Beware: Even relatively small graphs have a lot of edges (USair, with approx\. 1000 nodes, has approx\. 9000 edges), thus making this function costly. This function is parallellised.
    + *vulnerability*: Outcommented function. It gives the vulnerability for a general nodes and edge list. Not tested. Use at your own risk.
    
## Structure of objects
There are a couple of recurring objects in these scripts. Here they are described (for the full list of variables, look at the documentation of the functions themselfs):

+ *cl*: A cluster of computer kernels where the calculation should be done. Easiest choice is to initialize a cluster at the start of a session with *start\_cluster* from *system*. The kernels should be loaded with the functions, methods and variables that are used in the calculation. The defaults of *start\_cluster* are enough for the calculations in *functions*.
+ *g*: An igraph graph object. If a *l\_matrix* is used, the edges should have weights on them, otherwise weights of 1 are used.
+ *l*: A length matrix of size *n \* n*, with *n* the number of nodes of *g*. It gives for every pair of nodes their real life distance. Only the diagonal entries should be zero.
+ *t*: A transport matrix of size *n \* n*, with *n* the number of nodes of *g*. This matrix gives the amount of "traffic" from one node to another. For example, if ten passengers want to go from airport A to C and they need to go via B, the *t* matrix will be a three-by-three matrix containing zeros everywhere, except at the *[A,B]* entry, there it would be ten.
+ *performance*: A function of *g*, *l* and *t*, where the last two may be ignored, but should be accepted, that gives a form of measurement or fitness of the graph. Most often measures from *measures\_distance\.R* are used, but others are possible too. 











